# Generated by Django 4.0.2 on 2022-02-13 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=datetime.datetime(2022, 2, 13, 8, 35, 26, 851759, tzinfo=utc), max_length=30, verbose_name='FullName'),
            preserve_default=False,
        ),
    ]
